### PR TITLE
Fix package header and add package footer

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by narendraj9** [comment]
Hi! I have fixed a few things. How can see the byte compile warnings?

**Comment by syohex** [comment]
> How can see the byte compile warnings? 

- Open Emacs with minimum configuration(I recommend to use [Cask](https://github.com/cask/cask/))
- Open directory with dired where package files are
- type `B`(dired-do-byte-compile) and `yes`

**Comment by narendraj9** [comment]
How can I get informative byte compiler error messages? 

I have fixed most of the warnings and errors, I get none when I load my Emacs normally but when I do `emacs -Q` and then byte-compile I get errors of not being able to find files. The files belonging to the package.  These are the only errors left to be removed now:

```elisp

Compiling file /home/nj/.emacs.d/packages/rest/hledger-mode/hledger-helpers.el at Wed Oct 12 20:41:39 2016
hledger-helpers.el:31:1:Error: Cannot open load file: No such file or directory, popup

Compiling file /home/nj/.emacs.d/packages/rest/hledger-mode/hledger-mail.el at Wed Oct 12 20:41:40 2016
hledger-mail.el:28:1:Error: Cannot open load file: No such file or directory, hledger-core

Compiling file /home/nj/.emacs.d/packages/rest/hledger-mode/hledger-mode.el at Wed Oct 12 20:41:40 2016
hledger-mode.el:20:1:Error: Cannot open load file: No such file or directory, hledger-core

Compiling file /home/nj/.emacs.d/packages/rest/hledger-mode/hledger-reports.el at Wed Oct 12 20:41:40 2016
hledger-reports.el:28:1:Error: Cannot open load file: No such file or directory, hledger-core

Compiling file /home/nj/.emacs.d/packages/rest/hledger-mode/hledger-webservice.el at Wed Oct 12 20:41:40 2016
hledger-webservice.el:29:1:Error: Cannot open load file: No such file or directory, hledger-core

```

**Comment by syohex** [comment]
- Set load path of dependency(like `popup) and current directory by `-L . ` command line option.

**Comment by narendraj9** [comment]
Thanks! :-)

**Pull request merged**
